<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>

<div class="header-logo">
	<?php if ($block->isHomePage()):?>
		<strong class="logo" style="border-right: 0">
		<?php else: ?>
			<a class="logo" href="<?= $block->getUrl('') ?>" style="border-right: 0" title="<?= /* @escapeNotVerified */ $storeName ?>">
			<?php endif ?>
			<img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
			alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
			<?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
			<?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
			/>
			<?php if ($block->isHomePage()):?>
			</strong>
		<?php else:?>
		</a>
	<?php endif?>

	<span class="action nav-toggle icon-hamburger"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
</div>

