<?php
$_helper = $this->helper('ODBM\GoogleTagManager\Helper\Data');
?>
<?php if ($_helper->isEnabled()) : ?>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=<?php echo $_helper->getGtmCode(); ?>" height="0"
                width="0" style="display:none;visibility:hidden"></iframe>
    </noscript><!-- End Google Tag Manager (noscript) -->
<?php endif; ?>