<?php
/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $product = $block->getProduct(); ?>
<?php $attrValue = $product->getData('enable_custom_price'); ?>
<?php $type = $product->getTypeId(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($attrValue == '1') :
                if ($product->getTypeId() != 'bundle' || $product->getTypeId() != 'grouped') : ?>
                <div class="field custom-price-div">
                    <span><?php echo __('Custom Price'); ?> </span>
                    <span class="custom-price-currency">USD$</span>
                    <input class="input-text required custom-price" id="customPrice" name="customPrice" type="number" value="0">
                </div>
                <?php endif; ?>
            <?php endif; ?>
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?php echo __('Qty'); ?></span></label>
                    <div class="control">
                        <input type="number"
                               name="qty"
                               id="qty"
                               value="<?php echo $block->getProductDefaultQty() * 1 ;?>"
                               title="<?php echo __('Qty'); ?>"
                               class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                        />
                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
