version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - apt-add-repository -y ppa:ondrej/php && apt-get update
       - apt-get install -qqy --force-yes --no-install-recommends php7.2 libapache2-mod-php7.2 php7.2-common php7.2-gd php7.2-mysql php7.2-curl php7.2-intl php7.2-xsl php7.2-mbstring php7.2-zip php7.2-bcmath php7.2-iconv php7.2-soap php-xdebug vim strace
       - curl -sS https://getcomposer.org/installer | php
       - mv composer.phar /usr/local/bin/composer
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
       - composer install

  # post_build:
  #   commands:
  #      - ls
  #      - echo "Updating magento schema"
  #      - php ./bin/magento setup:upgrade
artifacts:
  files:
     - '**/*'
  discard-paths: no
#cache:
  #paths:
    # - paths
