version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
       - apt-add-repository -y ppa:ondrej/php && apt-get update
       - apt-get install -qqy --force-yes --no-install-recommends php7.0 php7.0-intl php7.0-soap php7.0-common php7.0-xml php7.0-gd php7.0-curl php7.0-mbstring php7.0-mysql php7.0-mcrypt php7.0-xsl php7.0-zip php7.0-bcmath php7.0-iconv php7.0-redis
       - curl -sS https://getcomposer.org/installer | php
       - mv composer.phar /usr/local/bin/composer
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
       - composer install
  #post_build:
    #commands:
      # - command
      # - command
artifacts:
  files:
     - '**/*'
  discard-paths: yes
#cache:
  #paths:
    # - paths
