web:
  build: .
  ports:
  - 80:80
  - 10004:9000
  volumes:
  - .:/magento
  links:
  - mysql
  - redis

mysql:
  image: mysql:5.6
  ports:
  - 10001:3306
  command: mysqld --user=root --verbose --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
  environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento_user
      MYSQL_PASSWORD: magento
  volumes:
  - ./docker/sql:/docker-entrypoint-initdb.d

redis:
  image: redis
