<?php /* @var $block \Experius\DonationProduct\Block\Product\Type\Donation */ ?>

<div class="product-options-wrapper" id="product-options-wrapper">
    <div class="fieldset">
        <div class="field">
            <label class="label">
                <span><?php echo __('Choose an amount to donate'); ?></span>
            </label>
            <div class="control">
                <div class="options-list nested" id="options-4-list">
                    <?php $itemCount = 0; ?>
                    <?php foreach ($block->getFixedAmounts() as $fixedAmount => $viewFixedAmount) : $itemCount++ ?>
                        <div class="field choice admin__field admin__field-option">
                            <input type="radio" class="radio admin__control-radio"
                                   name="amount_fixed"
                                   id="donation_option_<?= $itemCount ?>"
                                   value="<?php echo $fixedAmount; ?>"
                                   <?php echo ($itemCount === 1)? "checked" : "" ?>
                            >
                            <label class="label admin__field-label" for="donation_option_<?= $itemCount ?>"><span><?php echo $viewFixedAmount; ?></span></label>
                        </div>
                    <?php endforeach; ?>
                    <div class="field choice admin__field admin__field-option">
                        <input type="checkbox" class="radio admin__control-radio"
                               name="_recurring"
                               id="_recurring"
                               value="true"
                        >
                        <label class="label admin__field-label" for="_recurring"><span><?= __("Make donation recurring?") ?></span></label>
                    </div>
                </div>
            </div>
            <input type="hidden" name="_motivation_code" value="<?php echo $_REQUEST['motivation'] ?? ''; ?>" />
            <input type="hidden" name="_referer" value="<?php echo $_SERVER['HTTP_REFERER'] ?? ''; ?>" />

        </div>
        <div class="field">
            <label class="label">
                <span><?php echo __('Choose your own Amount %1 (minimum %2)', $block->getCurrencySymbol(), $block->getMinimalDonationAmount()); ?></span>
            </label>
            <div class="control">
                <input name="amount" id="amount" title="amount" placeholder="<?php echo $block->getCurrencySymbol(); ?>" class="input-text validate-number" type="text" data-validate="{required:false, 'validate-number': true}" value="">
            </div>
        </div>
    </div>
</div>