<?php /* @var $block \Experius\DonationProduct\Block\Product\Type\Donation */ ?>

<div class="product-options-wrapper" id="product-options-wrapper">
	<div class="fieldset">
		<?php if (!empty($block->getFixedAmounts())) : ?>
			<div class="field">
				<label class="label">
					<span><?php echo __('Choose an amount to donate'); ?></span>
				</label>
				<div class="control">
					<div class="options-list nested" id="options-4-list">
						<?php $itemCount = 0; ?>
						<?php foreach ($block->getFixedAmounts() as $fixedAmount => $viewFixedAmount) : $itemCount++ ?>
							<div class="field choice admin__field admin__field-option">
								<input type="radio" class="radio admin__control-radio"
								name="amount_fixed"
								id="donation_option_<?= $itemCount ?>"
								value="<?php echo $fixedAmount; ?>"
								<?php echo ($itemCount === 1)? "checked" : "" ?>
								>
								<label class="label admin__field-label" for="donation_option_<?= $itemCount ?>"><span><?php echo $viewFixedAmount; ?></span></label>
							</div>
						<?php endforeach; ?>

					</div>
				</div>
			</div>
		<?php endif; ?>
		<div class="field">

			<input type="hidden" name="_motivation_code" value="<?php echo $_REQUEST['motivation'] ?? ''; ?>" />
			<input type="hidden" name="_referer" value="<?php echo $_SERVER['HTTP_REFERER'] ?? ''; ?>" />
			<input type="hidden" name="_ministry" value="<?php echo $_REQUEST['ministry'] ?? '';?>" />

			<!--            <label class="label">-->
				<!--                <span>--><?php //echo __('Choose your own Amount %1 (minimum %2)', $block->getCurrencySymbol(), $block->getMinimalDonationAmount()); ?><!--</span>-->
				<!--            </label>-->
				<div class="control">
					<div class="restrain">
						<span class="currency"><?php echo $block->getCurrencySymbol(); ?></span>
						<input 
							name="amount" 
							id="amount" 
							title="Amount"
							placeholder="<?php echo __('Amount (USD)'); ?>"
							class="input-text validate-number" type="text" 
							data-msg-required="Please Enter a Valid Donation Amount"
							data-msg-number="Please Enter a Valid Donation Amount" 
							data-msg-validate-number="Please Enter a Valid Donation Amount" 
							data-validate="{required:true, 'validate-number': true, 'number': true}" 
							value="<?php echo ( !empty( $_GET['amount'] ) && is_numeric( $_GET['amount'] ) )  ? $_GET['amount'] : ''; ?>"
							tabindex="3"
						/>
					</div>
				</div>
			</div>
			
			<?php 
			//If one time payment then hide the monthly payment button
			$hideMonthly = $block->getProduct()->getData('one-time-donation');
			if($hideMonthly!=1){
				?>

			<div class="radio--button">

				<input type="radio" class="radio admin__control-radio"
				name="_recurring"
				id="_recurring-yes"
				value="true"
				>
				<label class="label admin__field-label" for="_recurring-yes" tabindex="4"><span><?= __("Give Monthly") ?></span></label>
			</div>
			<div class="radio--button">
				<input type="radio" class="radio admin__control-radio"
				name="_recurring"
				id="_recurring-no"
				value="false"
				>
				<label class="label admin__field-label" for="_recurring-no" tabindex="5"><span><?= __("Give Once") ?></span></label>
			</div>
			<?php  } ?>

			<script type="text/javascript">
				// Temporary redirect to MOS for recurring
				// Remove once recurring is ready to be handled through Magento
				var checkRedirectToMOS = function(e) {

					let amount = document.getElementById('amount').value;

					if ( !amount ) {
						// Check radio buttons
						var radios = document.getElementsByName('amount_fixed');

						for (var i = 0, length = radios.length; i < length; i++) {
							if (radios[i].checked) {
								amount = radios[i].value;
								break;
							}
						}
					}

					var sku = document.getElementsByName('_motivation_code')[0].value;

					if ( document.getElementById('_recurring-yes').checked ) {
						window.location.href = 'https://secure.ourdailybread.org/donation/?factor=' + sku + '&amount=' + amount +'&donation-options=monthly';

						e.preventDefault();
						return false;
					}
				};

				document.addEventListener('DOMContentLoaded', function() {
					var sku = document.getElementById('product_addtocart_form').dataset.productSku;

					if ( document.getElementsByName('_motivation_code')[0].value === '' ) {
						document.getElementsByName('_motivation_code')[0].value = sku;
					}

					document.getElementById('product-addtocart-button').addEventListener( 'click', checkRedirectToMOS );
					document.getElementById('product_addtocart_form').addEventListener( 'submit', checkRedirectToMOS );
				}, false);
			</script>
	</div>
</div>