<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php
if ($_product->getTypeId() === "donation") {
    $buttonTitle = __('Credit Card');
} else {
	$buttonTitle = __('Add to Cart');
}

?>

<?php if ($_product->isSaleable()): ?>
	<div class="box-tocart<?php if($_product->getData('one-time-donation')==1){echo ' oneTimeOnly';} //.onetimeonly unhides payment options ?>" style="display: none;">
		<div class="fieldset">
			<?php if ($block->shouldRenderQuantity()): ?>
				<div class="field qty">
					<label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
					<div class="control">
						<input type="number"
						name="qty"
						id="qty"
						value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
						title="<?= /* @escapeNotVerified */ __('Qty') ?>"
						class="input-text qty"
						data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
						/>
					</div>
				</div>
			<?php endif; ?>

			<p>Give your <span id="gifttype"><span class="ot">one-time</span><span class="rc">recurring</span></span> gift by</p>

			<div class="actions dntpmtoptbx">
				<button type="submit"
				title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
				class="action primary tocart"
				id="product-addtocart-button">
				<?php if ($buttonTitle == 'Credit Card'): ?>
					<img class="btnicon" src="<?php echo $this->getViewFileUrl('images/ccicon.png'); ?>" /> 
					<span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
				<?php else : ?>
					<span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
				<?php endif; ?>

			</button>
			<?= $block->getChildHtml('', true) ?>
		</div>
	</div>
</div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
	<script type="text/x-magento-init">
		{
			"#product_addtocart_form": {
			"Magento_Catalog/product/view/validation": {
			"radioCheckboxClosest": ".nested"
		}
	}
}
</script>
<?php else : ?>
	<script type="text/x-magento-init">
		{
			"#product_addtocart_form": {
			"Magento_Catalog/js/validate-product": {}
		}
	}
</script>
<?php endif; ?>
