<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Catalog\Block\Product\View $block
 */

$product = $block->getProduct();
//$image = //$this->_productHelper->getImageUrl($product); //$product->getImage();
$image = '';
//die('here');
?>

<style type="text/css">
	@media (min-width: 768px) {
		#maincontent.page-main {
	    background: url(<?= $image ?>) no-repeat !important;
	  }
	}
</style>