<?php
$_product = $block->getProduct();
$customPrice = 15.51;
$_product->setPrice($customPrice);
?>
<div class="fieldset">
    <div class="field">
        <div class="control">
            <div class="restrain">
                <span class="currency"></span>
                <input
                        name="amount"
                        id="amount"
                        title="Amount"
                        placeholder="$"
                        class="input-text validate-number" type="text"
                        data-msg-required="Please Enter a Valid Donation Amount"
                        data-msg-number="Please Enter a Valid Donation Amount"
                        data-msg-validate-number="Please Enter a Valid Donation Amount"
                        data-validate="{required:true, 'validate-number': true, 'number': true}"
                        value="<?php echo (!empty($_GET['amount']) && is_numeric($_GET['amount'])) ? $_GET['amount'] : ''; ?>"
                        tabindex="3"
                />
            </div>
        </div>
    </div>
</div>
