<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
?>
<?php 

$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();
$welcome_text = $block->getWelcome();
?>

<div class="header-logo">
	<?php if ($block->isHomePage()):?>
		<strong class="logo">
		<?php else: ?>
			<a class="logo" href="<?= $block->getUrl('') ?>" title="<?= /* @escapeNotVerified */ $storeName ?>">
			<?php endif ?>
			<img src="<?= /* @escapeNotVerified */ $block->getLogoSrc() ?>"
			alt="<?= /* @escapeNotVerified */ $block->getLogoAlt() ?>"
			<?= $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
			<?= $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
			/>
			<?php if ($block->isHomePage()):?>
			</strong>
		<?php else:?>
		</a>
	<?php endif?>

	<span class="header-tagline desktop-only"> <?= $welcome_text; ?> </span>
	<span class="action nav-toggle icon-hamburger"><span><?= /* @escapeNotVerified */ __('Toggle Nav') ?></span></span>
</div>

	<div class="header-tagline mobile-only"> <?= $welcome_text; ?> </div>

