<?php
$_product = $block->getProduct();
$viewModel = $block->getViewModel();
?>
<!-- START PRODUCT CUSTOMIZATIONS -->

<!-- START: Product Formats Block -->
<?php if ($_product->getData("format_options")):
    $_productFormatSkus = explode(", ", $_product->getData("format_options"));
    $_productFormats = array();
    $count = 0;
    $_productFormats = $viewModel->getProductsBySku($_productFormatSkus);
    ?>
    <?php if (!empty($_productFormats)) : ?>
    <div class="formats">
        <h3><?php echo __('Also available in the following formats:') ?></h3>
        <table class="data-table">
            <tbody>
            <?php foreach ($_productFormats as $_productFormat) :
                $count++;
                if (is_object($_productFormat)) {
                    $type = $_productFormat->getAttributeText('search_type');
                    $price = trim($_productFormat->getPrice(), "0");
                    $url = $_productFormat->getProductUrl();
                    $sku = $_productFormat->getSku();
                } else {
                    continue;
                }
                ?>
                <tr class="first <?php echo ($count % 2) ? "even" : "odd" ?>">
                    <th class="label">
                        <a href="<?php echo $url ?>"><?php echo $type ?></a>
                    </th>
                    <?php if ($price > 0): ?>
                        <td class="data">
                            Price: $<?php echo $price ?>
                        </td>
                    <?php else: ?>
                        <td class="data">
                            Price: See product page.
                        </td>
                    <?php endif; ?>
                    </a>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php endif; ?>
<?php endif; ?>
