<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<span class="nav-toggle icon-close"></span>
<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php
        // An example of a nested menu
    	// <li class="has-submenu"> <a href="#" <i class="submenu-arrow icon-chevron_left"></i> Languages </a>
    	// 		<ul class="submenu">
    	// 			<li> <a href="#"> Language One </a> </li>
    	// 			<li> <a href="#"> Language Two </a> </li>
    	// 		</ul>
    	// </li>
        ?>

        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>
