<?php
$intgt6 = $block->getTotalDonationsBySku("INTGT6");
$intgt7 = $block->getTotalDonationsBySku("INTGT7");
?>
<!--
Rob's open-roads script and html
- moved bulk of css to ODBM_Donation::view/frontend/web/css/openroads.css
- changed <i> to <em>
- changed s3 links to CloudFront
-->
<head>
    <link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('ODBM_Donation::css/openroads.css')?>">
</head>
<p>
    <script type="text/javascript" xml="space">
      require([
        'jquery'
      ], function ($) {
        $(document).ready(function () {
          var INTGT6current =<?php echo $intgt6 ?>;
          var INTGT7current =<?php echo $intgt7 ?>;

          var INTGT6goal = 75000;
          var INTGT7goal = 75000;

          var INTGT6pricematchtil = 0;
          var INTGT7pricematchtil = 7500;


          var INTGT6currentwithpricematch = (INTGT6current + (Math.min(INTGT6pricematchtil, INTGT6current)));
          var INTGT7currentwithpricematch = (INTGT7current + (Math.min(INTGT7pricematchtil, INTGT7current)));


          var INTGT6percent = ((INTGT6currentwithpricematch / INTGT6goal) * 100);
          var INTGT7percent = ((INTGT7currentwithpricematch / INTGT7goal) * 100);

          var rn = Math.floor(Math.random() * (4)) + 1;

          jQuery('#INTGT6percent').css({'width': INTGT6percent + '%'});
          jQuery('#INTGT6current').html('$' + INTGT6currentwithpricematch.toLocaleString());
          jQuery('#INTGT6goal').html('$' + INTGT6goal.toLocaleString());
          jQuery('#INTGT7percent').css({'width': INTGT7percent + '%'});
          jQuery('#INTGT7current').html('$' + INTGT7currentwithpricematch.toLocaleString());
          jQuery('#INTGT7goal').html('$' + INTGT7goal.toLocaleString());

        });
      });
      </script>
</p>
<div style="background-color: #ffffff; position: relative; min-height: 600px; width: 100%; margin-left: auto; margin-right: auto; font-family: 'PT Sans', sans-serif;">
    <div class="donctr" style="width: 100%;">
        <div class="bxwrap"
             style="display: flex; justify-content: space-between; color: #222222; text-align: center; flex-wrap: wrap; padding-top: 40px; padding-bottom: 40px; align-items: stretch;">
            <div id="INTGT6Box" class="onethirdbox" style="padding: 15px 0px;">
                <div class="boxshell"><img style="width: 100%;"
                                           src="https://d626yq9e83zk1.cloudfront.net/images/intgt1-2019sm.jpg"/>
                    <h3 class="causehdr" style="color: #222222; font-weight: bold; padding: 0 20px; text-align: left;">
                        Spread Hope in Africa with <span style="white-space: nowrap;"><em>Our Daily Bread</em></span></h3>
                    <p class="causetxt" style="color: #222222; padding: 0 20px; text-align: left;">Your gift will equip
                        <em>Our Daily Bread</em> writers in Africa to create content that speaks directly to the lives of
                        people in their region. Our team is working to enhance existing devotional resources and create
                        new ones that appeal to an African audience. Help us reach even more people with hope and
                        encouragement from God’s Word!</p>
                    <div class="barholder">
                        <div id="INTGT6percent" class="barpercent"></div>
                    </div>
                    <p class="raisedtxt" style="color: #222222; font-weight: normal; line-height: 1.4em;"><span
                                id="INTGT6current" style="font-weight: bold;"></span> raised of <span
                                id="INTGT6goal"></span> goal.</p>
                    <p style="margin-top: 30px; padding-bottom: 30px;"><a class="sptbtn" href="/intgt6.html">GIVE
                            NOW</a></p>
                </div>
            </div>
            <div id="INTGT7Box" class="onethirdbox" style="padding: 15px 0px;">
                <div class="boxshell"><img style="width: 100%;"
                                           src="https://d626yq9e83zk1.cloudfront.net/images/intgt2-2019sm.jpg"/>
                    <h3 class="causehdr" style="color: #222222; font-weight: bold; padding: 0 20px; text-align: left;">
                        Share God’s Love with Teens in the <span style="white-space: nowrap;">United States</span></h3>
                    <p class="causetxt" style="color: #222222; padding: 0 19px; text-align: left;">Partner with us help
                        teenagers in the U.S. find hope and spiritual stength for the struggles they face. Anxiety and
                        depression affect more young people today than ever before. Your gift will help us create and
                        distribute an <em>Our Daily Bread</em> devotional written specifically for teens. Together we can
                        reach them with God’s unconditional love!</p>
                    <div class="barholder">
                        <div id="INTGT7percent" class="barpercent"></div>
                    </div>
                    <p class="raisedtxt" style="color: #222222; font-weight: normal; line-height: 1.4em;"><span
                                id="INTGT7current" style="font-weight: bold;"></span> raised of <span
                                id="INTGT7goal"></span> goal.</p>
                    <p style="margin-top: 30px; padding-bottom: 30px;"><a class="sptbtn" href="/intgt7.html">GIVE
                            NOW</a></p>
                </div>
            </div>
        </div>
    </div>
    <div class="ftflex boxshell"
         style="text-align: center; display: block; background-color: #d93e00; margin-bottom: 50px;">
        <div style="padding: 7px 30px;">
            <h3 style="color: #ffffff; font-size: 24px; line-height: 27px; padding-bottom: 10px; font-weight: bold;">
                Can’t decide?<br/>Give where it is needed most.</h3>
            <p style="text-align: center; margin-top: 5px;"><a class="sptbtninv" href="/intgt8.html"><i
                            class="icon-support_filled"></i>GIVE NOW</a></p>
        </div>
    </div>
</div>