<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<?php
$_order = $block->getOrderItemsDetails();
$is_recurring = $block->isOrderRecurring();
$thankYouPage = $block->getCustomPage();
?>

<div class="checkout-success">



    <?php if(!empty($thankYouPage)): //If exists, display custom Thank You page ?>
    <div class="customthankyoupage">

        <?php echo $block->getLayout()
            ->createBlock('Dat\Thankyoupage\Block\CmsBlock')
            ->setBlockId($thankYouPage)
            ->setData( 'order_id', $block->escapeHtml($block->getOrderId()))
            ->setData('amount', sprintf("%01.2f", $_order->getGrandTotal()))
            ->setData('method', __('%1', sprintf('%s', $_order->getPayment()->getMethodInstance()->getTitle())))
            ->setData('first_name', $_order->getCustomerIsGuest() ? __('%1', sprintf('%s', $_order->getBillingAddress()->getFirstname())) : __('%1', sprintf('%s', $_order->getCustomerFirstName())))
            ->setData('freq', $is_recurring ? 'recurring' : 'one-time')
            ->toHtml();
        ?>






        <?php  else: ?>
        <div class="thankyoupage">







            <h1 class="ty">
                <?php if ( $is_recurring ): ?>
                    <?php if ($_order->getCustomerIsGuest()) :?>
                        <?php echo __('%1, thank you for becoming a Monthly Partner!', sprintf('%s', $_order->getBillingAddress()->getFirstname())) ?>
                    <?php  else: ?>
                        <?php echo __('%1, thank you for becoming a Monthly Partner!', sprintf('%s', $_order->getCustomerFirstName())) ?>
                    <?php endif; // is guest ?>
                <?php else: ?>

                <?php if ($_order->getCustomerIsGuest()) :?>
                    <?php echo __('%1, thank you for your support!', sprintf('%s', $_order->getBillingAddress()->getFirstname())) ?>
                <?php  else: ?>
                    <?php echo __('%1, thank you for your support!', sprintf('%s', $_order->getCustomerFirstName())) ?>
                <?php endif; // is guest ?>


            </h1>
            <?php if ($block->getOrderId()):?>
                <p class="giftdetailslabel">We appreciate your generous one-time gift of <span class="highlight"><?php echo $_order->formatPrice($_order->getGrandTotal()); ?></span> given by <span class="highlight"><?php echo $_order->getPayment()->getMethodInstance()->getTitle(); ?></span>.</p>
                <p class="giftdetailslabel">Your transaction number is <span class="highlight"><?php
                        if ($block->getCanViewOrder()) {
                            echo __(
                                '%1',
                                sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>',
                                    $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId())
                                )
                            );
                        } else {
                            echo $block->escapeHtml($block->getOrderId());
                        }
                        ?></span>.</p>
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('thankyousocial')->toHtml();?>



            <?php endif; ?>

            <?php endif; ?>

            <?php endif; ?>




            <?php
            if(!empty($block->hasGaData())){
                echo $block->getGaForm();
            }
            ?>

            <script>

                require(['domReady'], function (domReady) {
                    domReady(function () {
                        trySendCheckoutGA();
                    });
                });

            </script>
        </div>
    </div>
