<header id="header" class="page-header navbar-fixed-top">
    <div class="page-header-container">
        <div class="top-header">
            <!-- TODO REPLACE IMAGE PATHS -->
            <a class="logo" href="https://store.ourdailybread.org">
                <img src="https://store.ourdailybread.org/skin/frontend/rwd/odb/images/logo.svg" alt="Our Daily Bread Ministries" class="large" />
                <img src="https://store.ourdailybread.org/skin/frontend/rwd/odb/images/logo_small.svg" alt="Our Daily Bread Ministries" class="small" />
            </a>

            <div class="promo-msg">
                <?php echo "YOUR SUPPORT HELPS US SPREAD THE GOSPEL AROUND THE WORLD." // $this->getChildHtml('promo');?>
            </div>

            <div class="skip-links">
                <a href="#header-nav" class="skip-link skip-nav">
                    <span class="icon"></span>
                    <span class="label"><?php echo __('Menu'); ?></span>
                </a>

                <a href="#header-search" class="skip-link skip-search">
                    <span class="icon"></span>
                    <span class="label"><?php echo __('Search'); ?></span>
                </a>

                <div class="account-cart-wrapper">
                    <!-- Cart -->

                    <div class="header-minicart">
                        <?php echo "Minicart" // $this->getChildHtml('minicart_head'); ?>
                    </div>


                </div>


            </div>
        </div>
        
        <div class="nav">

            <!-- Navigation -->

            <div id="header-nav" class="skip-content">
                <?php echo "" //$this->getChildHtml('topMenu') ?>
            </div>

            <!-- Search -->

            <div id="header-search" class="skip-content">
                <?php echo "" //$this->getChildHtml('topSearch') ?>
            </div>
        
        </div>

        <!-- Account -->

        <div id="header-account" class="skip-content">
            <?php echo "" //$this->getChildHtml('topLinks') ?>
        </div>
    </div>
</header>

<?php echo "" //$this->getChildHtml('topContainer'); ?>
<?php echo "" //$this->getChildHtml('categoryheaderimage'); ?>
