<?php $_product = $block->getProduct(); ?>

<!-- if exists, display video_link -->
<?php $_video = $_product->getData("video_link");
if ($_video): ?>
    <div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%;">
        <iframe style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="<?php echo $_video ?>" frameborder='0' allowfullscreen></iframe>
    </div>
<?php endif; ?>
