<?php
$_product = $block->getProduct();
$stockItem = $_product->getExtensionAttributes()->getStockItem();
?>
<!-- <div class="float-right"> TODO: Float-right around custom prices feature -->
<?php if ($_product->isAvailable() && !$_product->getPreorder()): ?>
    <p class="availability in-stock"><?php echo __('Availability:') ?> <span><?php echo (int)$stockItem->getQty() > 0 ? (int)$stockItem->getQty() . " " . __('left'): __('In stock') ?></span></p>
    <meta itemprop="availability" content="http://schema.org/InStock">
<?php elseif ($_product->getData("preorder") == 1): ?>
    <p class="availability out-of-stock preorder-info"><?php echo __('Availability:') ?> <span><?php echo __('Preorder') ?></span></p>
    <p class="clear-fix preorder-info" style="color: red;">Ships after: <?php echo date("M. d", strtotime($_product->getData("pubdate"))) ?></p>
<?php else: ?>
    <p class="availability out-of-stock"><?php echo __('Availability:') ?> <span><?php echo __('Out of stock') ?></span></p>
    <meta itemprop="availability" content="http://schema.org/OutOfStock">
<?php endif; ?>
<!-- </div> -->
