apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  virtual.conf: |
    upstream fastcgi_backend {
        server  unix:/var/run/php-fpm/www.sock;
    }

    map $http_host $MAGE_RUN_CODE {
        default base;
        ${PREFIX}ourdailybreadpublishing.org dhp_us;
        ${PREFIX}dhespanol.org dh_sp;
        ${PREFIX}store.ourdailybread.org odb_store_view;
        ${PREFIX}store.christianuniversity.org storecc_org;
        ${PREFIX}donations.ourdailybread.org odb_donations;
        ${PREFIX}moto.ourdailybreadpublishing.org moto;
    }

    map $http_host $type {
        hostnames;
        default                  website;
        pmo.ourdailybread.org    store;
        ${PREFIX}store.ourdailybread.org  store;
        ${PREFIX}moto.ourdailybreadpublishing.org  store;
    }

    server {
        listen 80;
        server_name ${PREFIX}donations.ourdailybread.org ${PREFIX}ourdailybreadpublishing.org ${PREFIX}dhespanol.org ${PREFIX}store.ourdailybread.org ${PREFIX}store.christianuniversity.org ${PREFIX}moto.ourdailybreadpublishing.org;
        set $MAGE_ROOT /usr/share/nginx/html/magento;
        root $MAGE_ROOT;
        set $MAGE_RUN_TYPE $type; #or set $MAGE_RUN_TYPE store;
        # set $MAGE_MODE production;
        access_log   /usr/share/nginx/html/magento-access.log;
        error_log    /usr/share/nginx/html/magento-error.log;
        # include /usr/share/nginx/html/magento/magento.conf;
    }

    server {
        server_name www.discoveryhouse.org.uk discoveryhouse.org.uk www.ourdailybreadpublishing.org.uk;
        return 301 $scheme://ourdailybreadpublishing.org.uk$request_uri;
    }
