<?php
$_product = $block->getProduct();
$viewModel = $block->getViewModel();
?>
<!-- START PRODUCT CUSTOMIZATIONS -->

<!--  START: Display video_link -->
<?php $_video = $_product->getData("video_link");
if ($_video): ?>
    <div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; margin-bottom: 20px;">
        <iframe style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="<?php echo $_video ?>"
                frameborder='0' allowfullscreen></iframe>
    </div>
<?php endif; ?>
<!--  END: Display video_link -->

<!-- START: Product Formats Block -->
<?php if ($_product->getData("format_options")):
    $_productFormatSkus = explode(", ", $_product->getData("format_options"));
    $_productFormats = array();
    $count = 0;

    $_productFormats = $viewModel->getProductsBySku($_productFormatSkus);

    usort($_productFormats, function ($a, $b) {
        if (is_object($a) && is_object($b)) {
            return $a->getPrice() > $b->getPrice();
        }
    });
    ?>
    <?php if (!empty($_productFormats)) : ?>
    <div class="formats">
        <ul id="formats">
            <?php foreach ($_productFormats as $_productFormat) :
                if (is_object($_productFormat)) {
                    $type = $_productFormat->getAttributeText('search_type');
                    $url = $_productFormat->getProductUrl();
                    $sku = $_productFormat->getSku();
                    $count++;
                } else {
                    continue;
                }
                ?>
                <a href="<?php echo $url ?>">
                    <li <?= ($count > 3) ? "class='hide'" : "" ?>>
                        <?php if ($_productFormat->getTypeId() == 'downloadable'
                            && current($_productFormat->getTypeInstance(true)->getLinks($_productFormat))->getPrice() > $_productFormat->getPrice()) : ?>
                            <?php echo $type ?> <!--TODO: Price label and currency symbol hardcoded to English and $ -->
                            <span
                                    class="float-right">Price: $<?= number_format($_productFormat->getTypeInstance(true)->getLinks($_productFormat)->getPrice(), 2); ?></span>
                        <?php else : ?>
                            <?php echo $type ?> <span
                                    class="float-right">Price: $<?= number_format($_productFormat->getPrice(), 2); ?></span>
                        <?php endif; ?>
                    </li>
                </a>
            <?php endforeach; ?>
        </ul>
        <?php if ($count > 3): ?>
            <div id="formats-button"
                 style="cursor: pointer; border-bottom: solid thin #3190EC; margin-bottom: 5px;">
                <p><i class="icon fa fa-chevron-down"></i>Show more formats</p>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
    <script type="text/javascript">
			jQuery("div.formats").on('click', function () {
				if (!jQuery("#formats").hasClass('active')) {
					jQuery("#formats").addClass('active');
					jQuery("#formats-button").html('<i class="icon fa fa-chevron-up"></i>Show less');
					jQuery("#formats li.hide").slideDown(200);
				} else {
					jQuery("#formats").removeClass('active');
					jQuery("#formats-button").html('<i class="icon fa fa-chevron-down"></i>Show more formats');
					jQuery("#formats li.hide").slideUp(200);
				}
			});
    </script>
<?php endif; ?>
<!-- START: Product Formats Block -->

<!-- START: Product Download Options -->
<?php if ($_product->getData("itunes") || $_product->getData("amazon") || $_product->getData("google_play")): ?>
    <div class="mp3-buttons">
        <div style="cursor: pointer; border-bottom: solid thin #3190EC;">
            <p class="mp3-options"><i
                        class="icon fa fa-chevron-down"></i><?= ($_product->getAttributeSetId() == 16) ? "eBook Formats" : "Digital Music Formats"; ?>
            </p>
        </div>
        <ul id="downloads" style="display: none;">
            <?php if ($_product->getData("itunes")) : ?>
                <a href="<?php echo $_product->getData("itunes") ?>" alt="Buy Music from iTunes"
                   target="itunes_store">
                    <li class="itunes">
                        <img src="<?php echo ($_product->getAttributeSetId() == 16) ? $block->getViewFileUrl('images/ibooks_75sq.png') : $block->getViewFileUrl('images/itunes_75sq.png') ?>"
                             alt="Buy from iTunes"> <?php echo ($_product->getAttributeSetId() == 16) ? "iBooks" : "iTunes" ?>
                    </li>
                </a>
            <?php endif; ?>

            <?php if ($_product->getData("amazon")) : ?>
                <a href="<?php echo $_product->getData("amazon") ?>" alt="Buy Music from Amazon"
                   target="about_blank">
                    <li class="amazon">
                        <img src="<?php echo ($_product->getAttributeSetId() == 16) ? $block->getViewFileUrl('images/kindle_75sq.png') : $block->getViewFileUrl('images/amazon_75sq.png') ?>"
                             alt="Buy from Amazon"> Amazon
                    </li>
                </a>
            <?php endif; ?>

            <?php if ($_product->getData("google_play")) : ?>
                <a href="<?php echo $_product->getData("google_play") ?>" alt="Buy Music from Google Play"
                   target="about_blank">
                    <li class="google">
                        <img src="<?php echo($block->getViewFileUrl('images/googleplay_75sq.png')) ?>"
                             alt="Buy from Google Play"> Google Play
                    </li>
                </a>
            <?php endif; ?>
        </ul>
    </div>
    <script type="text/javascript">
			jQuery("div.mp3-buttons").on('click', function () {
				if (!jQuery("#downloads").hasClass('active')) {
					jQuery(".mp3-buttons div").css({borderBottom: "none"});
					jQuery(".mp3-buttons i.icon").removeClass('fa-chevron-down').addClass('fa-chevron-up');
					jQuery("#downloads").addClass('active').slideDown(200);
				} else {
					jQuery(".mp3-buttons div").css({borderBottom: "solid thin #3190EC"});
					jQuery(".mp3-buttons i.icon").removeClass('fa-chevron-up').addClass('fa-chevron-down');
					jQuery("#downloads").removeClass('active').slideUp(200);
				}
			});
    </script>
<?php endif; ?>
<!-- END: Product Download Options -->