<?php

$code = $block->escapeHtml($block->getMethodCode());
$ccType = $block->getInfoData('cc_type');
$ccExpMonth = $block->getInfoData('cc_exp_month');
$ccExpYear = $block->getInfoData('cc_exp_year');
$cards = $block->getCustomerCards();

$extraClass = $switchSubscriptionHtml = '';
$switchSubscription = $block->getSwitchSubscriptionBlock();
if ($switchSubscription)
{
  $extraClass = $switchSubscription->extraClass;
  $switchSubscriptionHtml = $switchSubscription->toHtml();
}

?>
<fieldset id="payment_form_cryozonic_stripe" class="cryozonic-stripe standard-form admin__fieldset indent-target stripe-new" <?php echo $block->hideIfNotBuggy(); ?>>

<?php echo $switchSubscriptionHtml; ?>

<fieldset class="admin__fieldset payment-method stripe-new <?php echo $extraClass; ?> cryozonic-stripe" id="payment_form_cryozonic_stripe_payment">

  <?php if (!empty($cards)): ?>
    <div class="cryozonic-saved-cards-section" id="saved-cards">
      <?php foreach ($cards as $key => $card): ?>
        <div class="cryozonic-saved-card">
          <input type="radio" name="payment[cc_saved]" class="select"
                value="<?php echo $card->id . ':' . $card->brand . ':' . $card->last4; ?>" id="<?php echo $card->id; ?>"
            >
          <label for="<?php echo $card->id; ?>">
            <span class="type <?php echo $card->brand ?>">
                <?php echo (empty($card->brand) ? __('Card') : $block->cardType($card->brand)); ?>
            </span>
            <span class="last4 cryozonic-stripe-fade"><?php echo __('ending in'); ?> <?php echo $card->last4; ?></span>
            <span class="exp cryozonic-stripe-fade"><?php echo __('expires'); ?>
                <?php echo str_pad($card->exp_month,2,'0',STR_PAD_LEFT); ?>/<?php echo $card->exp_year; ?>
            </span>
          </label>
        </div>
      <?php endforeach; ?>

      <div>
        <input type="radio" name="payment[cc_saved]" value="new_card" class="select" id="new_card" checked="checked">
        <label for="new_card">
          <span class="type"><?php echo __('Use a new card'); ?></span>
        </label>
      </div>
    </div>
  <?php endif; ?>

  <?php echo $block->getLayout()->createBlock('Cryozonic\StripePayments\Block\StripeElements')->toHtml(); ?>

  <?php if (!$block->isNewCustomer()): ?>
  <div class="field admin__field stripe-new">
    <label class="admin__field-label" for="cryozonic_stripe_cc_save">
      <input type="checkbox"
        title="<?php echo $block->escapeHtml(__('Save card for future purchases')); ?>"
        class="admin__control-cc-save stripe-input"
        id="cryozonic_stripe_cc_save"
        name="payment[cc_save]"
        checked="checked"/>
      <span><?php echo $block->escapeHtml(__('Save card for future purchases')); ?></span>
    </label>
  </div>
  <?php endif; ?>

</fieldset>

<script type="text/javascript">
  require(['jquery', 'prototype', 'mage/mage'], function(jQuery, $) {
    jQuery(document).ready(function()
    {
      var securityMethod = '<?php echo $block->config->getSecurityMethod(); ?>';
      var stripeJsPublishableKey = '<?php echo $block->config->getPublishableKey(); ?>';
      if (securityMethod > 0)
      {
        initStripe(stripeJsPublishableKey, securityMethod);
        cryozonic.initAdminStripeJs();
        cryozonic.isAdmin = true;
      }
      cryozonic.initAdminEvents();
    });
  });
</script>

</fieldset>
