<?php /* @var $block \ODBM\Donation\Block\Product\Type\OdbDonation */ ?>

<div class="donation-product product-options-wrapper <?php echo $block->useCustomTemplate() ? 'custom' : ''; ?>" id="product-options-wrapper">

	<?php if ( !$block->useCustomTemplate() ): ?>
		<div class="title-box">
			<h2> <?php echo __('You can help...'); ?></h2>
			<h1> <?php echo $block->getPromoTitle(); ?></h1>
		</div>

		<style type="text/css">
			#product-options-wrapper {
				background-image: url(<?php echo $block->getBackgroundImage('large'); ?>)
			}

			@media only screen and (max-width: 767px) {
				#product-options-wrapper {
					background-image: url(<?php echo $block->getBackgroundImage('small'); ?>)
				}
			}

			@media only screen and (max-width: 992px) and (min-width: 768px) {
				#product-options-wrapper {
					background-image: url(<?php echo $block->getBackgroundImage('medium'); ?>)
				}
			}
		</style>
	<?php endif; ?>

	<?php if ( $description = $block->getProduct()->getDescription() ): ?>
		<div class="description-box">
			<a class="description-toggle" href="#"><em><?php echo __('Learn More'); ?></em></a>
			<div class="hidden description-inner">
				<span class="description-toggle icon-close"></span>
				<div class="description-inner-content">
				<?php echo $description; ?>
				</div>
			</div>
		</div>
	<?php endif; ?>


	<div class="fieldset">
		<?php if (!empty($block->getFixedAmounts())) : ?>
			<div class="field">
				<label class="label">
					<span><?php echo __('Choose an amount to donate'); ?></span>
				</label>
				<div class="control">
					<div class="options-list nested" id="options-4-list">
						<?php $itemCount = 0; ?>
						<?php foreach ($block->getFixedAmounts() as $fixedAmount => $viewFixedAmount) : $itemCount++ ?>
							<div class="field choice admin__field admin__field-option">
								<input type="radio" class="radio admin__control-radio"
								name="amount_fixed"
								id="donation_option_<?= $itemCount ?>"
								value="<?php echo $fixedAmount; ?>"
								<?php echo ($itemCount === 1)? "checked" : "" ?>
								>
								<label class="label admin__field-label" for="donation_option_<?= $itemCount ?>"><span><?php echo $viewFixedAmount; ?></span></label>
							</div>
						<?php endforeach; ?>

					</div>
				</div>
			</div>
		<?php endif; ?>
		<div class="field">

			<input type="hidden" name="_motivation_code" value="<?php echo $_REQUEST['motivation'] ?? ''; ?>" />
			<input type="hidden" name="_referer" value="<?php echo $_SERVER['HTTP_REFERER'] ?? ''; ?>" />
			<input type="hidden" name="_ministry" value="<?php echo $_REQUEST['ministry'] ?? '';?>" />

			<!--            <label class="label">-->
				<!--                <span>--><?php //echo __('Choose your own Amount %1 (minimum %2)', $block->getCurrencySymbol(), $block->getMinimalDonationAmount()); ?><!--</span>-->
				<!--            </label>-->
				<div class="control">
					<div class="restrain">
						<span class="currency"><?php echo $block->getCurrencySymbol(); ?></span>
						<input 
							name="amount" 
							id="amount" 
							title="Amount"
							placeholder="<?php echo __('Amount').(' (').$block->getCurrentCurrencyCode().(')'); ?>"
							class="input-text validate-number" type="text" 
							data-msg-required="Please Enter a Valid Donation Amount"
							data-msg-number="Please Enter a Valid Donation Amount" 
							data-msg-validate-number="Please Enter a Valid Donation Amount" 
							data-validate="{required:true, 'validate-number': true, 'number': true}" 
							value="<?php echo ( !empty( $_GET['amount'] ) && is_numeric( $_GET['amount'] ) )  ? $_GET['amount'] : ''; ?>"
							tabindex="3"
						/>
					</div>
				</div>
			</div>
			
			<?php 
			//If one time payment then hide the monthly payment button
			$hideMonthly = $block->getProduct()->getData('one_time_donation');
			if($hideMonthly!=1){
				?>

			<div class="radio--button">

				<input type="radio" class="radio admin__control-radio"
				name="_recurring"
				id="_recurring-yes"
				value="true"
				>
				<label class="label admin__field-label" for="_recurring-yes" tabindex="4"><span data-cy="givemonthly"><?= __("Give Monthly") ?></span></label>
			</div>
			<div class="radio--button">
				<input type="radio" class="radio admin__control-radio"
				name="_recurring"
				id="_recurring-no"
				value="false"
				>
				<label class="label admin__field-label" for="_recurring-no" tabindex="5"><span data-cy="giveonce"><?= __("Give Once") ?></span></label>
			</div>
			<?php  } ?>

        <script>
            require(['jquery', 'domReady!'], function ($) {
                'use strict';

                // disable "Credit Card" button and change text
                const disableCartButton = function (e) {
                    document.querySelector("#product-addtocart-button > span").style.display = 'none';
                    document.getElementById('product-addtocart-button').classList.add('disabled');
                    const addText = document.createTextNode("Adding...");
                    document.getElementById("product-addtocart-button").appendChild(addText);
                };

                // hides the PayPal logo and adds text
                const disablePayPalButton = function (e) {
                    document.querySelector("[data-action='checkout-form-submit']").style.display = 'none';
                    document.querySelector(".paypal.checkout").classList.add('disabled');
                    const addText = document.createTextNode("Adding...");
                    document.querySelector(".paypal.checkout").appendChild(addText);
                };

                const skuElement = document.getElementById('product_addtocart_form');
                const jsProduckSku = skuElement.dataset ? skuElement.dataset.productSku : 'unknown_sku';

                if (document.getElementsByName('_motivation_code')[0].value === '') {
                    document.getElementsByName('_motivation_code')[0].value = jsProduckSku;
                }

                document.getElementById('product-addtocart-button').addEventListener('click', disableCartButton, {once: true});
                document.querySelector("[data-action='checkout-form-submit']").addEventListener('click', disablePayPalButton, {once: true});
            });
        </script>

			<?php $block->getChildHtml(); ?>
	</div>
</div>